### ISSUE TITLE
训练完结果如何显示

### ISSUE THREAD

**Issue by ldj0o** [JunchenLiu77/NeRRF#1]
请问训练完的结果该如何显示出来呢？

**Comment by ldj0o** [comment]
为什么我训练完成后tet_visual和visuals是空的呢？

**Comment by JunchenLiu77** [comment]
Hi! The mesh learned in the first stage is saved in NeRRF/data/learned_geo and the DMTet parameters are saved in NeRRF/checkpoints/[EXPNAME]/_renderer.
tet_visual folder is used to visualize the result of stage 2.

**Comment by ldj0o** [comment]
Thank you bro, if it is convenient, can you leave a contact information such as wechat, and later I would like to ask you some questions

**Comment by JunchenLiu77** [comment]
OK, my wechat number is ljc13303512288.
