### ISSUE TITLE
The environment.yml seems to have some version conflicts

### ISSUE THREAD

**Issue by elenacliu** [JunchenLiu77/NeRRF#2]
For example, kaolin 0.12.0 is not compatible with scipy 1.9.3.

```
kaolin 0.12.0 requires scipy<=1.7.2,>=1.2.0, but you have scipy 1.7.3 which is incompatible.
```

And I installed the environment from scratch without torch in the environment. When the script installed chamferdist==1.0.0, it ran into an import error because the setup.py for chamferdist needed to import torch, which did not exist in my conda environment by then. So maybe you can move the torch requirement to the top of the pip requirement list?

**Comment by JunchenLiu77** [comment]
Thanks for your reporting the issue! The environment.yml file will be update later.
